version: 2.1
orbs:
  bc-orb: evrons/bc-orb@2.0.0
jobs:
  run-checkov:
    executor: bc-orb/default
    steps:
      - checkout
      - bc-orb/checkov:
          output: 'json'
workflows:
  checkov:
    jobs:
      - run-checkov
