version: 2.1
orbs:
  node: circleci/node@1.1.6
  bc-orb: evrons/bc-orb@0.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - bc-orb/greet:
          greeting: "allahu akbar"

workflows:
    build-and-test:
      jobs:
        - build-and-test
