version: 2.1
orbs:
  node: circleci/node@1.1.6
  greet: evrons/bc-orb
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - greet:
        greeting: 'allahu akbar'
workflows:
    build-and-test:
      jobs:
        - build-and-test